# Numpy Exercises

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.20.3


In [3]:
a = np.array([[1,2,3],[4,5,6]])

In [9]:
b = np.array([[10,11,12],[13,14,15]])

In [10]:
c = a+b

In [11]:
print(c)

[[11 13 15]
 [17 19 21]]


In [12]:
d = a*2

In [13]:
print(d)

[[ 2  4  6]
 [ 8 10 12]]


In [17]:
i = np.identity(4)

In [18]:
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array re-dimensioning
*Convert a 1-D array to a 3-D array*

In [22]:
a = np.array([x for x in range(27)])
o = a.reshape(3,3,3)
print(o)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]


In [20]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [21]:
print(type(a))

<class 'numpy.ndarray'>
